name: "Scrypted"
description: "Scrypted is a home automation platform powered by node.js."
version: "v0.4.1.lite"
url: https://github.com/dshafik/haos-addons
slug: "scrypted"
init: false
panel_icon: mdi:pound
webui: "http://[HOST]:[PORT:11080]"
image: "koush/scrypted"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  10443/tcp: 10443
  11080/tcp: 11080
host_network: true
environment:
  SCRYPTED_VOLUME: "/data"
  SCRYPTED_CAN_RESTART: "false"
  SCRYPTED_INSECURE_PORT: "11080"

